<a href="https://colab.research.google.com/github/FoxJaeger007/Clases-de-Analisis-de-dato/blob/main/Laboratorio_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Parte 1 ejercicio 1 - Crear un DataFrame con los nombres, profesión y países de 8 personas, y luego imprimir el DataFrame.

import pandas as pd

# Crear un diccionario con los datos
datos = {
    'Nombre': ['Ana', 'Carlos', 'Laura', 'Juan', 'María', 'Pedro', 'Lucía', 'Marta'],
    'Profesión': ['Ingeniera', 'Médico', 'Abogada', 'Profesor', 'Artista', 'Carpintero', 'Diseñadora', 'Científica'],
    'País': ['España', 'México', 'Argentina', 'Chile', 'Colombia', 'Perú', 'Uruguay', 'Brasil']
}

# Crear el DataFrame
df = pd.DataFrame(datos)

# Imprimir el DataFrame
print(df)


   Nombre   Profesión       País
0     Ana   Ingeniera     España
1  Carlos      Médico     México
2   Laura     Abogada  Argentina
3    Juan    Profesor      Chile
4   María     Artista   Colombia
5   Pedro  Carpintero       Perú
6   Lucía  Diseñadora    Uruguay
7   Marta  Científica     Brasil


In [8]:
# Parte 1 --	Cargar un archivo CSV (puedes usar un archivo de ejemplo en tu entorno) y mostrar las primeras 5 filas.

import pandas as pd

# Leer el archivo CSV
df = pd.read_csv('Laboratorio_6.csv', sep=";")

# Mostrar las primeras filas del DataFrame
print(df.head(5))


   id     cedula nombres y apellidos           direccion     celular  \
0   1   45673849        ANA GONZALEZ        cl 2 #123-34  3114562728   
1   2   38755920          BERTA CRUZ   carrera 3 # 23-23  3108976542   
2   3  867433939    ROBERTO     RIOS        cl 32 #45-23  3004567283   
3   4  387575741         MARIACASTRO  carrera 32 # 34-43  3057893245   
4   5   12234421      MARRRIA   RIOS      cl132 #145-123  3125578930   

      correo electronico      pais valor factura  servicio fecha instalacion  
0           ag@gmail.com  Colombia   $ 45.000,00     Hogar         3/05/2023  
1      berta@hotmail.com  Colombia   $ 34.876,00     Hogar        30/06/2022  
2             Sin Correo     Chile   $ 23.456,00  Comercio         8/06/2024  
3      mcastro@yahoo.com     Chile   $ 45.000,00  Comercio               NaN  
4  lindatriana@gmail.com     Japon  $ 450.000,00  Comercio        20/04/2022  


In [3]:
# Parte 1 -	Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios, y luego mostrar un resumen estadístico de los datos.

import pandas as pd
import numpy as np

# Generar un DataFrame con valores aleatorios
data = np.random.randn(100, 8)  # 100 filas y 8 columnas de valores aleatorios
columnas = ['Columna1', 'Columna2', 'Columna3', 'Columna4', 'Columna5', 'Columna6', 'Columna7', 'Columna8']

df = pd.DataFrame(data, columns=columnas)

# Mostrar un resumen estadístico de los datos
resumen_estadistico = df.describe()
print(resumen_estadistico)


         Columna1    Columna2    Columna3    Columna4    Columna5    Columna6  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean    -0.049261    0.062971    0.046680    0.119234    0.162262   -0.163862   
std      0.938233    1.022730    0.918367    0.995381    0.992635    1.083099   
min     -3.405875   -1.833517   -2.158260   -2.316335   -2.057483   -3.314381   
25%     -0.630173   -0.725829   -0.599450   -0.469321   -0.535611   -0.834626   
50%     -0.176652   -0.056841    0.068714    0.103066    0.215181   -0.110505   
75%      0.527928    0.633692    0.829102    0.762527    0.771352    0.526648   
max      2.546142    2.715532    1.870177    2.278513    2.686689    3.287534   

         Columna7    Columna8  
count  100.000000  100.000000  
mean     0.036937    0.042479  
std      1.097694    1.052685  
min     -2.833485   -3.713147  
25%     -0.717453   -0.520718  
50%      0.219414    0.012910  
75%      0.841034    0.546853  
max      2.310

In [9]:
#Parte 2 -	Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo.


import numpy as np

# Crear un array de números del 1 al 10
array = np.arange(1, 11)

# Calcular la suma
suma = np.sum(array)

# Calcular la media
media = np.mean(array)

# Calcular el valor máximo
maximo = np.max(array)

# Mostrar los resultados
print(f"Array: {array}")
print(f"Suma: {suma}")
print(f"Media: {media}")
print(f"Valor Máximo: {maximo}")


Array: [ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Media: 5.5
Valor Máximo: 10


In [10]:
#Parte 2 - -	Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6

import numpy as np

# Crear un array de 3x4 lleno de ceros
array_3x4 = np.zeros((3, 4))

# Mostrar el array original
print("Array 3x4 original:")
print(array_3x4)

# Cambiar la forma del array a 2x6
array_2x6 = array_3x4.reshape(2, 6)

# Mostrar el array con la nueva forma
print("Array 2x6 después de reshape:")
print(array_2x6)


Array 3x4 original:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array 2x6 después de reshape:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
# Parte 2 - -	Generar una matriz aleatoria de 3x3 y calcular su transpuesta.

import numpy as np

# Generar una matriz aleatoria de 3x3
matriz_3x3 = np.random.rand(3, 3)

# Calcular la transpuesta de la matriz
matriz_transpuesta = matriz_3x3.T

# Mostrar la matriz original y su transpuesta
print("Matriz 3x3 original:")
print(matriz_3x3)

print("\nMatriz transpuesta:")
print(matriz_transpuesta)


Matriz 3x3 original:
[[0.06675827 0.11882493 0.62897167]
 [0.59047772 0.62095598 0.15392879]
 [0.55110193 0.34693785 0.41974915]]

Matriz transpuesta:
[[0.06675827 0.59047772 0.55110193]
 [0.11882493 0.62095598 0.34693785]
 [0.62897167 0.15392879 0.41974915]]


In [12]:
# Parte 2 -	Concatenar dos arrays de NumPy, cada uno con 5 valores, y luego imprimir el array concatenado.

import numpy as np

# Crear dos arrays de NumPy con 5 valores cada uno
array1 = np.array([1, 2, 8, 4, 4])
array2 = np.array([5, 10, 10, 9, 11])

# Concatenar los dos arrays
array_concatenado = np.concatenate((array1, array2))

# Imprimir el array concatenado
print("Array concatenado:")
print(array_concatenado)


Array concatenado:
[ 1  2  8  4  4  5 10 10  9 11]


# New Section